## Goals:
Overarching goal:
Generate figure 2 in alpaca paper
https://arxiv.org/pdf/1807.08912.pdf
1. Implement Alpaca
2. Generate figure 


## Next:
3. implement MOCA (if too hard, try MAML)
    * https://arxiv.org/pdf/1912.08866.pdf
    * https://arxiv.org/pdf/1703.03400.pdf
4. implement segment detection (not just changepoint detection)
5. find a lunar soil simulator

In [12]:
import math
import numpy as np
import torch
import yaml

from alpaca_pytorch import *
from dataset import *

In [13]:
cfg_filename = 'configs/sinusoid-config.yml'
with open(cfg_filename,'r') as ymlfile:
    config = yaml.load(ymlfile, Loader=yaml.FullLoader)

In [14]:
dataset = SinusoidDataset(config)

In [15]:
agent = ALPaCA(config, sess1, g1)

NameError: name 'sess1' is not defined

In [21]:
torch.diag(torch.tensor(np.array([1,2,3])))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [22]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
torch.reshape()

TypeError: reshape() missing 2 required positional argument: "input", "shape"

In [39]:
# sigma_eps = List([1,2,3])
sigma_eps = 0.2
y_dim = 3

In [40]:
sigma_eps is list

False

In [41]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [42]:
if sigma_eps is list:
    SigEps = torch.diag(torch.tensor(np.array(sigma_eps)))
else:
    SigEps = sigma_eps*torch.eye(y_dim)
SigEps = torch.reshape(SigEps, (1,1,y_dim,y_dim))

In [43]:
SigEps

tensor([[[[0.2000, 0.0000, 0.0000],
          [0.0000, 0.2000, 0.0000],
          [0.0000, 0.0000, 0.2000]]]])

In [ ]:
torch